### ISSUE TITLE
akka.logger-startup-timeout property in application.conf

### ISSUE THREAD

**Issue by grohan2002** [deric/kafka-manager-docker#1]
Are we missing "akka.logger-startup-timeout" property in application .conf ?
As it is recently added in kafka-manager [1.3.3.17](https://github.com/yahoo/kafka-manager/compare/1.3.3.17...master)

**Comment by deric** [comment]
Good catch, sorry I've overlooked that. I'll recompile the image and push it to docker hub.

**Comment by deric** [comment]
I'm trying to recompile the image, but I'm unable to resolve all sbt dependencies :(
```
[error] (*:update) sbt.ResolveException: download failed: org.javassist#javassist;3.19.0-GA!javassist.jar(bundle)
[error] download failed: org.bouncycastle#bcpkix-jdk15on;1.52!bcpkix-jdk15on.jar
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? 
```

**Comment by Arttii** [comment]
@deric I am getting the same error, did you find a way to solve it?

**Comment by deric** [comment]
@Arttii Unfortunately it seems to be impossible to create a reliable sbt build inside Docker :(. I've created an issue for this: #2.

**Comment by deric** [comment]
@Arttii try latest version from master, it should be fixed.
